## Numpy

In [1]:
# loading the numpy package
import numpy as np

In [2]:
# check the version
np.__version__

'1.15.4'

In [4]:
#create a list comprising numbers from 0 to 9
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
#converting integers to string in a loop - this style of handling lists is known as list comprehension.
[str(c) for c in L]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

[type(item) for item in L]
[int, int, int, int, int, int, int, int, int, int]

[int, int, int, int, int, int, int, int, int, int]

In [13]:
#creating arrays
np.zeros(10, dtype='int')
np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])




array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=float)
np.array([[ 1.,  1.,  1.,  1.,  1.],
      [ 1.,  1.,  1.,  1.,  1.],
      [ 1.,  1.,  1.,  1.,  1.]])


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#creating a matrix with a predefined value
np.full((3,5),1.23)
np.array([[ 1.23,  1.23,  1.23,  1.23,  1.23],
      [ 1.23,  1.23,  1.23,  1.23,  1.23],
      [ 1.23,  1.23,  1.23,  1.23,  1.23]])


array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [16]:
#create an identity matrix
np.eye(3)
np.array([[ 1.,  0.,  0.],
      [ 0.,  1.,  0.],
      [ 0.,  0.,  1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#set a random seed
np.random.seed(0)


x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension


print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
('x3 ndim:', 3)
('x3 shape:', (3, 4, 5))
('x3 size: ', 60)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


('x3 size: ', 60)

In [20]:
# Array Slicing
x = np.arange(10)
x
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#from start to 4th position
x[:5]
np.array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [22]:
#from 4th position to end
x[4:]
np.array([4, 5, 6, 7, 8, 9])

array([4, 5, 6, 7, 8, 9])

In [23]:
#from 4th to 6th position
x[4:7]
np.array([4, 5, 6])

array([4, 5, 6])

In [29]:
#return elements at even place
x[ : : 2]
np.array([0, 2, 4, 6, 8])

array([0, 2, 4, 6, 8])

In [30]:
#return elements from first position step by two
x[1::2]
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [31]:
#reverse the array
x[::-1]
np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Pandas

In [32]:
# load package Pandas
import pandas as pd

In [40]:
#create a data frame - dictionary is used here where keys get converted to column names and values to row values.
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [41]:
#We can do a quick analysis of any data set using:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [42]:
#Among other things, it shows the data set has 5 rows and 2 columns with their respective names.
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
Country    5 non-null object
Rank       5 non-null int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [43]:
#Let's create another data frame.
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [44]:
#Let's sort the data frame by ounces - inplace = True will make changes to the data
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [45]:
#create another data with duplicated rows
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [46]:
# loading csv files
df = pd.read_csv('card_data.csv')
df

Series_reference   Period  Data_value  Suppressed STATUS    UNITS  \
0       ECTA.S19A1  2001.03         NaN         NaN      C  Dollars   
1       ECTA.S19A1  2002.03         NaN         NaN      C  Dollars   
2       ECTA.S19A1  2003.03         NaN         NaN      C  Dollars   
3       ECTA.S19A1  2004.03     28005.1         NaN      F  Dollars   
4       ECTA.S19A1  2005.03     30629.6         NaN      F  Dollars   
5       ECTA.S19A1  2006.03     33317.4         NaN      F  Dollars   
6       ECTA.S19A1  2007.03     36422.0         NaN      F  Dollars   
7       ECTA.S19A1  2008.03     39198.0         NaN      F  Dollars   
8       ECTA.S19A1  2009.03     40629.4         NaN      F  Dollars   

   Magnitude                                        Subject  \
0          6  Electronic Card Transactions (ANZSIC06) - ECT   
1          6  Electronic Card Transactions (ANZSIC06) - ECT   
2          6  Electronic Card Transactions (ANZSIC06) - ECT   
3          6  Electronic Card Transactions (ANZSIC06) - ECT   
4          6  Electronic Card Transactions (ANZSIC06) - ECT   
5          6  Electronic Card Transactions (ANZSIC06) - ECT   
6          6  Electronic Card Transactions (ANZSIC06) - ECT   
7          6  Electronic Card Transactions (ANZSIC06) - ECT   
8          6  Electronic Card Transactions (ANZSIC06) - ECT   

                                               Group Series_title_1  \
0  Total values - Electronic card transactions A/...         Actual   
1  Total values - Electronic card transactions A/...         Actual   
2  Total values - Electronic card transactions A/...         Actual   
3  Total values - Electronic card transactions A/...         Actual   
4  Total values - Electronic card transactions A/...         Actual   
5  Total values - Electronic card transactions A/...         Actual   
6  Total values - Electronic card transactions A/...         Actual   
7  Total values - Electronic card transactions A/...         Actual   
8  Total values - Electronic card transactions A/...         Actual   

         Series_title_2  Series_title_3  Series_title_4  Series_title_5  
0  RTS total industries             NaN             NaN             NaN  
1  RTS total industries             NaN             NaN             NaN  
2  RTS total industries             NaN             NaN             NaN  
3  RTS total industries             NaN             NaN             NaN  
4  RTS total industries             NaN             NaN             NaN  
5  RTS total industries             NaN             NaN             NaN  
6  RTS total industries             NaN             NaN             NaN  
7  RTS total industries             NaN             NaN             NaN  
8  RTS total industries             NaN             NaN             NaN

In [47]:
# show top columns
df.head()

Series_reference   Period  Data_value  Suppressed STATUS    UNITS  \
0       ECTA.S19A1  2001.03         NaN         NaN      C  Dollars   
1       ECTA.S19A1  2002.03         NaN         NaN      C  Dollars   
2       ECTA.S19A1  2003.03         NaN         NaN      C  Dollars   
3       ECTA.S19A1  2004.03     28005.1         NaN      F  Dollars   
4       ECTA.S19A1  2005.03     30629.6         NaN      F  Dollars   

   Magnitude                                        Subject  \
0          6  Electronic Card Transactions (ANZSIC06) - ECT   
1          6  Electronic Card Transactions (ANZSIC06) - ECT   
2          6  Electronic Card Transactions (ANZSIC06) - ECT   
3          6  Electronic Card Transactions (ANZSIC06) - ECT   
4          6  Electronic Card Transactions (ANZSIC06) - ECT   

                                               Group Series_title_1  \
0  Total values - Electronic card transactions A/...         Actual   
1  Total values - Electronic card transactions A/...         Actual   
2  Total values - Electronic card transactions A/...         Actual   
3  Total values - Electronic card transactions A/...         Actual   
4  Total values - Electronic card transactions A/...         Actual   

         Series_title_2  Series_title_3  Series_title_4  Series_title_5  
0  RTS total industries             NaN             NaN             NaN  
1  RTS total industries             NaN             NaN             NaN  
2  RTS total industries             NaN             NaN             NaN  
3  RTS total industries             NaN             NaN             NaN  
4  RTS total industries             NaN             NaN             NaN

In [48]:
df.columns

Index(['Series_reference', 'Period', 'Data_value', 'Suppressed', 'STATUS',
       'UNITS', 'Magnitude', 'Subject', 'Group', 'Series_title_1',
       'Series_title_2', 'Series_title_3', 'Series_title_4', 'Series_title_5'],
      dtype='object')

In [49]:
df.tail()

Series_reference   Period  Data_value  Suppressed STATUS    UNITS  \
4       ECTA.S19A1  2005.03     30629.6         NaN      F  Dollars   
5       ECTA.S19A1  2006.03     33317.4         NaN      F  Dollars   
6       ECTA.S19A1  2007.03     36422.0         NaN      F  Dollars   
7       ECTA.S19A1  2008.03     39198.0         NaN      F  Dollars   
8       ECTA.S19A1  2009.03     40629.4         NaN      F  Dollars   

   Magnitude                                        Subject  \
4          6  Electronic Card Transactions (ANZSIC06) - ECT   
5          6  Electronic Card Transactions (ANZSIC06) - ECT   
6          6  Electronic Card Transactions (ANZSIC06) - ECT   
7          6  Electronic Card Transactions (ANZSIC06) - ECT   
8          6  Electronic Card Transactions (ANZSIC06) - ECT   

                                               Group Series_title_1  \
4  Total values - Electronic card transactions A/...         Actual   
5  Total values - Electronic card transactions A/...         Actual   
6  Total values - Electronic card transactions A/...         Actual   
7  Total values - Electronic card transactions A/...         Actual   
8  Total values - Electronic card transactions A/...         Actual   

         Series_title_2  Series_title_3  Series_title_4  Series_title_5  
4  RTS total industries             NaN             NaN             NaN  
5  RTS total industries             NaN             NaN             NaN  
6  RTS total industries             NaN             NaN             NaN  
7  RTS total industries             NaN             NaN             NaN  
8  RTS total industries             NaN             NaN             NaN

In [50]:
df.isnull()

Series_reference  Period  Data_value  Suppressed  STATUS  UNITS  Magnitude  \
0             False   False        True        True   False  False      False   
1             False   False        True        True   False  False      False   
2             False   False        True        True   False  False      False   
3             False   False       False        True   False  False      False   
4             False   False       False        True   False  False      False   
5             False   False       False        True   False  False      False   
6             False   False       False        True   False  False      False   
7             False   False       False        True   False  False      False   
8             False   False       False        True   False  False      False   

   Subject  Group  Series_title_1  Series_title_2  Series_title_3  \
0    False  False           False           False            True   
1    False  False           False           False            True   
2    False  False           False           False            True   
3    False  False           False           False            True   
4    False  False           False           False            True   
5    False  False           False           False            True   
6    False  False           False           False            True   
7    False  False           False           False            True   
8    False  False           False           False            True   

   Series_title_4  Series_title_5  
0            True            True  
1            True            True  
2            True            True  
3            True            True  
4            True            True  
5            True            True  
6            True            True  
7            True            True  
8            True            True

In [51]:
df.isnull().sum()

Series_reference    0
Period              0
Data_value          3
Suppressed          9
STATUS              0
UNITS               0
Magnitude           0
Subject             0
Group               0
Series_title_1      0
Series_title_2      0
Series_title_3      9
Series_title_4      9
Series_title_5      9
dtype: int64

#### LAB: Using matplotlib, visualize the data given

More practicing resources:
[1]: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles-with-solutions.ipynb

[2]: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb
